name: dart_main_website
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.0
  mustache_template: ^2.0.0
  firedart: ^0.9.8
  equatable: ^2.0.7
  envied: ^1.1.1
  dio: ^5.8.0+1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  pdf_merger: ^0.0.6

  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.14
  envied_generator: ^1.1.0
